### ISSUE TITLE
Add redesigned numbers section for assets, crimininal cases, attendance

### ISSUE THREAD

**Issue by thedivtagguy** [thedivtagguy/whoismyneta#10]

**Comment by thedivtagguy** [comment]
The attendance, criminal cases and assets section needs to be redone to the following layout: 
![image](https://github.com/thedivtagguy/whoismyneta/assets/6006888/97cd0095-4f80-4cf5-a0a7-5ca65dbe8105)

**Comment by anirudhgovind** [comment]
I'm jumping in on this.
