### ISSUE TITLE
Remove box around search field

### ISSUE THREAD

**Issue by thedivtagguy** [thedivtagguy/whoismyneta#12]
![image](https://github.com/thedivtagguy/whoismyneta/assets/6006888/074e12c1-73e5-44ea-843f-c33b2ee7203c)

**Comment by divyanshkul** [comment]
![image](https://github.com/thedivtagguy/whoismyneta/assets/34028379/9f74ba37-266f-4562-b61c-e7313a1dc280)
you mean like this?
or the inner text field box?
