### ISSUE TITLE
Make it easier to locate yourself. 

### ISSUE THREAD

**Issue by thedivtagguy** [thedivtagguy/whoismyneta#4]
> Can you link this with google maps. I just type my address, and it picks everything else: Constituency, candidates, performances, promises made, funds received, funds spent.

https://twitter.com/anim2407/status/1783406448657232107

Geocoding or a locate me function would be helpful I think.

**Comment by iambibhas** [comment]
Does layerchart have any API to figure out if a coordinate exist inside a geometry in the geojson file? Or do we use something else?
